"""empty message

Revision ID: 066edd0adf40
Revises: 6e0c74680d9d
Create Date: 2022-07-21 14:10:42.757389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066edd0adf40'
down_revision = '6e0c74680d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('loses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'loses')
    op.drop_column('user', 'wins')
    # ### end Alembic commands ###
