"""empty message

Revision ID: 6e0c74680d9d
Revises: f1fbe42fa5b8
Create Date: 2022-06-22 19:56:26.792740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0c74680d9d'
down_revision = 'f1fbe42fa5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pslot1', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('pslot2', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('pslot3', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('pslot4', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('pslot5', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pslot5')
    op.drop_column('user', 'pslot4')
    op.drop_column('user', 'pslot3')
    op.drop_column('user', 'pslot2')
    op.drop_column('user', 'pslot1')
    # ### end Alembic commands ###
